- build.sh
- facts/mylist.py
- facts/myredis.py
- facts/queue.py
- server.py
- tests/test_mylist.py
- tests/test_redis.py
@flopezag 
Fixing multitenacy bug
Fixing gunicorn deployment.
> Fixing multitenacy bug

- sonar-project.properties
Align the code with the metrics file
@geonexus
> fix: rel: updating sonar properties @minor

- build.sh
- requirements_dev.txt
- tests/test_facts.py
@flopezag 
fixing some dependencies, adding sudo to some commands and giving permissions to some folders
> Fixing cobertura 

- .coveragerc
- .gitchangelog.rc
- README.rst
- requirements_dev.txt
- setup.cfg
- setup.py
@flopezag 
- Fixing badge of coveralls
- Adding GitChangelog config file
- Adding Pypi setup to publish the package.
> Adding coveralls fixing

- .travis.yml
- README.rst
- setup.py
- sonar-project.properties
@flopezag 
- release 1.1.0
- Fixed coveralls badge
- added pypi, coveralls, travis support
> release 1.1.0

- facts/mylist.py
- server.py
- tests/test_mylist.py
- tests/test_redis.py
@flopezag 
There was an error in the sum of the lists. The serverId should not be concatenated
https://jirapdi.tid.es/browse/CLAUDIA-4602
> Bug fixing

- facts/mylist.py
- server.py
- tests/test_mylist.py
- tests/test_redis.py
@flopezag 
There was a bug into REDIS QUEUE
> Fixing a bug into multitenacy queue

- facts/config.py
- facts/myredis.py
- requirements.txt
- server.py
- tests/test_redis.py
@flopezag 
Defined the size of the temporal window in the facts component in the configuration file
Insert the date & time in the redis together with the value of the data that it is received from the Orion CB.
If the 1st and last value is greater than or equal to the temporal window,we delete the queue and insert the last value on it.
Written Unit Test of the execution of this US
> Improving Signal Stability Component.

- .gitchangelog.rc
- server.py
- setup.py
- sonar-project.properties
@flopezag 
Preparing release 1.2.0
> New Release

- README.rst
- conf/fiware-facts.cfg
- facts/cloto_client.py
- facts/config.py
- facts/myredis.py
- requirements.txt
- server.py
- tests/test_cloto_client.py
- tests/test_redis.py
@flopezag 
Added window size support in order to control the values of each tenant from data received from cloto component into a rabbit queue.
If fiware-facts does not have any windowsize, asks cloto component to get the information.
> Added Windows Size support for tenants

- tests/test_redis.py
@flopezag 
Implemented the unit tests related to the multitenacy user story.
> Implement the unit test related to the multitenacy user story.

- .gitchangelog.rc
- server.py
- setup.py
- sonar-project.properties
> new: dev: Preparing release @minor

- README.rst
@jframos 
Fixing missing badges in README file
> Fixing missing badges in README file

- build.sh
@flopezag 
Changed condition where jenkins should check if it is a travis build or a jenkins build
> Updating build.sh file to build in jenkins

- server.py
Fixed imprecision while parsing from string to a number.
> Fixing imprecision while parsing from string to a number.

- server.py
@jframos 
Added the new attributes when a CB notification is received
> Added the new attributes when a CB notification is received

- server.py
@jframos 
removed quotes from the name attribute when it is added to rabbit message
> removed quotes from the name attribute when it is added to rabbit message

- requirements.txt
@jframos 
Adding new dependencies to fix oslo errors with keystoneclient
> Adding new dependencies to fix oslo errors with keystoneclient

- CHANGELOG
- README.rst
@jframos @pratid 
moving CHANGELOG to a separated file
Writing README file according to Guidelines
> Writing README file according to Guidelines

- README.rst
- build.sh
- facts/server.py
- tests/test_facts.py
- server file moved to facts package.
- new unit tests to test server.
- Improved the way to execute server and tests executions
> refactoring structure of the project to improve unit tests

- README.rst
- facts/config.py
- facts/server.py
- setup.py
- version is now into default config file.
- Configuration is now loaded from a cfg depending on the operating system or it is recovered from a environment variable location.
- Server checks if configuration file is complete or need more configuration.
> Fixing configuration issues with pip installation

- tests/acceptance/README.rst
- tests/acceptance/commons/constants.py
- tests/acceptance/commons/custom_asserts.py
- tests/acceptance/commons/rabbit_utils.py
- tests/acceptance/conf/logging.conf
- tests/acceptance/conf/settings.json
- tests/acceptance/doc/dsl.rst
- tests/acceptance/features/component/context_update.feature
- tests/acceptance/features/component/environment.py
- tests/acceptance/features/component/info.feature
- tests/acceptance/features/component/steps/context_update.py
- tests/acceptance/features/component/steps/info.py
- tests/acceptance/features/component/steps/window_size.py
- tests/acceptance/features/component/window_size.feature
- tests/acceptance/fiwarefacts_client/window_size_model_utils.py
- tests/acceptance/requirements.txt
@flopezag @geonexus 
This PR resolves the feature *CLAUDIA-4733*. This code implements some acceptance tests for *CLAUDIA-4259*. Main features included:
- RabbitMQ Consumer and Publisher for testing purposes.
- Test cases for FACTS' window size behavior
Locally.
> [QA] Window size test features

- README.rst
@jframos 
adding new comment about gunicorn logging
> adding new comment about gunicorn logging

- tests/test_facts.py
- tests/test_mylist.py
- tests/test_queue.py
> Adding more tests and improving the previous ones

- facts/myredis.py
- facts/server.py
@jframos 
- fixing windowsize value before adding it to the redis queue.
- fixing time stamp validation when windowsize is two
- Fixing the number of facts stored into a redis queue
- improved data parsing from context broker
- fixed server crashes when windowsize is equal to one.
>  rabbit message bug

- facts/myredis.py
@jframos 
- fixing bug during insert windowsize operation
> fixing bug during insert windowsize operation

- facts/server.py
@jframos 
- fixing behavior in the condition
> fixing behavior in the condition.

- tests/acceptance/features/component/multi_tenancy.feature
- tests/acceptance/features/component/signal_stability.feature
- tests/acceptance/features/component/window_size.feature
@flopezag @geonexus 
Untag scenarios (resolved bugs)
Locally
> [QA] Remove tags (resolved bugs)

- tests/acceptance/requirements.txt
@geonexus 
Missing requirement for acceptance tests
> [QA] Missing requirement

- tests/acceptance/features/component/context_update.feature
@geonexus 
After bugfixing, the bug _CLAUDIA-5519_ is reproduced with all mising params.
> [QA] Add tag of detected bug

- build.sh
- facts/server.py
- tests/test_redis.py
- fixing unit test errors
- fixed log message when a windowsize is received
- added xunit report to build file.
> fixing unittests

- README.rst
@jframos 
MySQL-devel package is now specified as prerequisite in the installation guide.
> MySQL-devel package added to doc

- facts/server.py
- tests/acceptance/features/component/context_update.feature
- tests/test_facts.py
- Adding exception control to some no-managed situations.
- Adding tests to check the use case: exception control to some no-managed situations.
> Validate context attribute values

- build.sh
- tests/acceptance/features/component/context_update.feature
@jframos 
- Fixing acceptance tests with values out of range.
> Fixing acceptance tests with values out of range.

- tests/acceptance/features/component/context_update.feature
@geonexus 
Minor fix for acceptance tests after bugfixing.
Locally.
> [QA] Fix acceptance tests after bugfixing

- README.rst
- utils/facts_start
- utils/fiware-facts.conf
- Added instructions and scripts to run with supervisor.
> Instructions and scripts to run with supervisor.

- facts/constants.py
- facts/server.py
@flopezag 
- new file with constants added.	
- Python dicts are using constants instead of strings.
> Constants in python dicts

- README.rst
- facts/config.py
- facts_conf/fiware-facts.cfg
@flopezag 
- The max timestamp between facts is now inside the configuration properties file.
> Maximum time between facts is now a property in the configuration file

- utils/integration/develenv/PolicyManager-Facts-1-Build_config.xml
- utils/integration/develenv/PolicyManager-Facts-3-Deploy_config.xml
- utils/integration/develenv/PolicyManager-Facts-4-Acceptance_config.xml
- utils/integration/develenv/PolicyManager-Facts_config.xml
@pratid 
- Add Jenkins config files to utils directory
> Add Jenkins config files to utils directory

- README.rst
@pratid    
Update docker badget
documentation
> update docker badget

- README.rst
- doc/_static/mystyle.css
- doc/conf.py
- doc/index.rst
@hmunfru 
Fix readthedocs documentation
Verified
> Fix readthedocs documentation

- facts/cloto_db_client.py
- tests/test_cloto_client.py
- tests/test_facts.py
@jesuspg  
Remove hardcode db name in facts
dockers
> Remove hardcoded database

- README.rst
- docker/README.md
@flopezag  
improving doc
nothing to do
> improving doc
